// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADKCTXjGHdriVymdRh1kyI32vxdLaGOxQ',
    appId: '1:1044428184305:web:66174a806d8d9974e32750',
    messagingSenderId: '1044428184305',
    projectId: 'todo-a-60a02',
    authDomain: 'todo-a-60a02.firebaseapp.com',
    storageBucket: 'todo-a-60a02.firebasestorage.app',
    measurementId: 'G-2QTXN04F5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQzxtHRgbd87dYAEAjtFqO0m49rAVZBxA',
    appId: '1:1044428184305:android:db226fbae2dbb1ace32750',
    messagingSenderId: '1044428184305',
    projectId: 'todo-a-60a02',
    storageBucket: 'todo-a-60a02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCf8OX6PI8q5Kz-kWq-pObtFTkHJ6jxqA',
    appId: '1:1044428184305:ios:fba1578bfe171bc1e32750',
    messagingSenderId: '1044428184305',
    projectId: 'todo-a-60a02',
    storageBucket: 'todo-a-60a02.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCf8OX6PI8q5Kz-kWq-pObtFTkHJ6jxqA',
    appId: '1:1044428184305:ios:fba1578bfe171bc1e32750',
    messagingSenderId: '1044428184305',
    projectId: 'todo-a-60a02',
    storageBucket: 'todo-a-60a02.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADKCTXjGHdriVymdRh1kyI32vxdLaGOxQ',
    appId: '1:1044428184305:web:ccc0c724f2a4e605e32750',
    messagingSenderId: '1044428184305',
    projectId: 'todo-a-60a02',
    authDomain: 'todo-a-60a02.firebaseapp.com',
    storageBucket: 'todo-a-60a02.firebasestorage.app',
    measurementId: 'G-TTJGNDSJ9S',
  );
}
